steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-docker.pkg.dev/liquidity-registry/liquidityio/indexer:${_TAG}'
      - '-t'
      - 'us-docker.pkg.dev/liquidity-registry/liquidityio/indexer:${_VERSION}'
      - '.'
images:
  - 'us-docker.pkg.dev/liquidity-registry/liquidityio/indexer:${_TAG}'
  - 'us-docker.pkg.dev/liquidity-registry/liquidityio/indexer:${_VERSION}'
substitutions:
  _TAG: dev
  _VERSION: latest
options:
  machineType: E2_HIGHCPU_8
timeout: 600s
